name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get the tag string
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_ENV"
    - name: Build the Docker image
      env:
        VERSION: ${{ env.VERSION }}
      run: docker build . --file Dockerfile --tag ghcr.io/legalmachinelab/facilex:$VERSION
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push images to kubernetes
      env:
        VERSION: ${{ env.VERSION }}
      run: |
        docker push ghcr.io/legalmachinelab/facilex:$VERSION
        docker tag ghcr.io/legalmachinelab/facilex:$VERSION ghcr.io/legalmachinelab/facilex
        docker push ghcr.io/legalmachinelab/facilex
    - name: Install kompose
      run: |
        curl -L https://github.com/kubernetes/kompose/releases/download/v1.32.0/kompose-linux-amd64 -o kompose
        chmod +x kompose
    - name: Run kompose
      run: | 
        ./kompose convert -f docker-compose.yml --replicas 2
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: kubectl apply -f . || echo ERROR